config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"

  post "sign_in", to: "sessions#create", as: :sign_in
  post "sign_out", to: "sessions#destroy", as: :sign_out

  get "/auth/twitter/callback", to: "sessions#create"

  resources :tweets, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  default_scope { order(tid: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    sign_in
    redirect_to root_path
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def sign_in
    session[:user_id] = user.id
    TwitterService.new(user).store_timeline
  end

  def sign_out
    session[:user_id] = nil
    @current_user = nil
  end

  def user
    find_user || sign_up
  end

  def find_user
    User.find_by(uid: auth[:uid])
  end

  def sign_up
    User.create(
      name: auth[:info][:name],
      uid: auth[:uid],
      oauth_token: auth[:credentials][:token],
      oauth_secret: auth[:credentials][:secret],
      picture: auth[:info][:image],
    )
  end

  def auth
    request.env["omniauth.auth"]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    render locals: { tweets: tweets }
  end

  private

  def tweets
    return nil unless current_user
    current_user.tweets.page params[:page]
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def create
    TwitterService.new(current_user).tweet(params[:tweet][:text])
    redirect_to root_path
  rescue Twitter::Error::Forbidden
    flash[:error] = "Your tweet is too long!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleTwitter Client</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>

  <body>
    <h1>Simple Twitter Client</h1>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/static_pages/index.html.erb
<% if current_user %>
  <div class="current-user">
    <div class="greetings">Hello, <%= current_user.name %>!</div>
    <div class="button sign-out"><%= link_to "Sign Out", sign_out_path, method: :post %></div>
  </div>

  <div class="post-tweet">
    <%= form_for :tweet, url: tweets_path do |f| %>
      <%= f.text_area :text, maxlength: 280, placeholder: "What's happening?" %>
      <%= f.submit "Tweet", class: "button" %>
    <% end %>
  </div>

  <div class="tweets">
    <% tweets.each do |tweet| %>
      <p><%= tweet.text.html_safe %></p>
    <% end %>
    <div class="pagination">
      <%= paginate tweets %>
    </div>
  </div>


<% else %>
<div class="button-container">
  <div class="button sign-in"><%= link_to "Sign in with Twitter", "/auth/twitter" %></div>
</div>
<% end %>